# Generated by Django 3.1.4 on 2021-01-06 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Page', '0002_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='pic',
        ),
    ]
